name: Python Application

on:
  schedule:
    - cron: '* * * * *'  # This cron expression runs the workflow every minute

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run main.py
        run: python3 main.py

      - name: Send mail
        uses: dawidd6/action-send-mail@v3
          with:
            server_address: smtp.gmail.com
            server_port: 587
            username: ${{secrets.MAIL_USERNAME}}
            password: ${{secrets.MAIL_PASSWORD}}
            subject: 'Datetime is: '
            to: parsapournabi1382@gmail.com
            from: NearNo
            html_body: file://README.md
            convert_markdown: true
